name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Tests skipped - you can add them later"

      - name: Check PR type
        id: pr-type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          
          if [[ $PR_TITLE == *"Bump"* ]] && [[ $PR_TITLE == *"patch"* ]]; then
            echo "safe-update=true" >> $GITHUB_OUTPUT
          else
            echo "safe-update=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto-merge safe updates
        if: steps.pr-type.outputs.safe-update == 'true'
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}" \
            --subject "Auto-merge: ${{ github.event.pull_request.title }}" \
            --body "Automatically merged Dependabot dependency update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add review label
        if: steps.pr-type.outputs.safe-update == 'false'
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" \
            --add-label "needs-review,major-update"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify PR status
        run: |
          echo "Dependabot PR processing completed"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Safe Update: ${{ steps.pr-type.outputs.safe-update }}"
